name: hanzi_util2
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
    #sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2
  cupertino_icons: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/unicode/Blocks.txt
    - assets/unicode/CJKRadicals.txt
    - assets/unicode/CJKRadicalsWithStrokes.txt
    - assets/unicode/Unihan_IRGSources.txt
    - assets/unicode/Unihan_OtherMappings.txt
    - assets/unicode/Unihan_RadicalStrokeCounts.txt
    - assets/unicode/Unihan_Readings.txt
    - assets/unicode/Unihan_Variants.txt

    - assets/fonts/HanaMinA.yaml
    - assets/fonts/HanaMinB.yaml
    - assets/fonts/NotoSerifCJKjp-Regular.yaml
    - assets/fonts/NotoSerifCJKkr-Regular.yaml
    - assets/fonts/NotoSerifCJKsc-Regular.yaml
    - assets/fonts/NotoSerifCJKtc-Regular.yaml
    #- assets/fonts/TH-Sung-PP0.yaml
    #- assets/fonts/TH-Sung-PP2.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Noto Serif CJK JP
      fonts:
        - asset: fonts/NotoSerifCJKjp-Regular.otf
    - family: Noto Serif CJK SC
      fonts:
        - asset: fonts/NotoSerifCJKsc-Regular.otf
    - family: Noto Serif CJK TC
      fonts:
        - asset: fonts/NotoSerifCJKtc-Regular.otf
    - family: Noto Serif CJK KR
      fonts:
        - asset: fonts/NotoSerifCJKkr-Regular.otf

  #  - family: Source Han Serif
  #    fonts:
  #      - asset: fonts/SourceHanSerif-Regular.otf
  #  - family: Source Han Serif TC
  #    fonts:
  #      - asset: fonts/SourceHanSerifTC-Regular.otf
  #  - family: Source Han Serif SC
  #    fonts:
  #      - asset: fonts/SourceHanSerifSC-Regular.otf
  #  - family: Source Han Serif K
  #    fonts:
  #      - asset: fonts/SourceHanSerifK-Regular.otf

  #  # basic, Extension-A
  #  - family: TH-Sung-PP0
  #    fonts:
  #      - asset: fonts/TH-Sung-PP0.ttf
  #  # Extension-B, C, D, E, F
  #  - family: TH-Sung-PP2
  #    fonts:
  #      - asset: fonts/TH-Sung-PP2.ttf

    - family: HanaMinA
      fonts:
        - asset: fonts/HanaMinA.ttf
    - family: HanaMinB
      fonts:
        - asset: fonts/HanaMinB.ttf

    - family: Monospace
      fonts:
        - asset: fonts/Inconsolata.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
